services:
  upload-blob:
    build:
      context: ./apps/upload-blob
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - environments/upload-blob.env
    networks:
      - njmtech-network
    restart: always

  media:
    build:
      context: ./apps/upload-blob
      dockerfile: apps/media/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - environments/media.env
    networks:
      - njmtech-network
    restart: always
    depends_on:
      - upload-blob

  yt-transcribe:
    build:
      context: ./apps/yt-transcribe
      dockerfile: Dockerfile
    env_file:
      - environments/yt-transcribe.env
    networks:
      - njmtech-network
    restart: always
    depends_on:
      - upload-blob

  blob-cron:
    build:
      context: ./apps/blob-cron
      dockerfile: Dockerfile
    volumes:
      - ./apps/blob-cron/src:/app/src
      - ./apps/blob-cron/main.py:/app/main.py
    env_file:
      - environments/blob-cron.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - njmtech-network
    restart: always

networks:
  njmtech-network:
    driver: bridge
