/**
 * Represents a single parsed line from a video transcript.
 * Timestamp is null for lines that have no timing marker.
 */
export interface TranscriptLine {
  /** Formatted timestamp string e.g. "00:01:23", or null if absent */
  timestamp: string | null;
  /** The spoken text content of this line */
  text: string;
}

/**
 * Visual variants for the AI exploration panel.
 */
export type AIPanelVariant = "popup" | "card";

/**
 * A suggested question generated by AI.
 */
export type PillQuestion = string;
